
** [IocConfig]`http://www.fantomfactory.org/pods/afIocConfig` values for Sitemap.
mixin SitemapConfigIds {

	** If set to 'true', 'Sitemap' automatically scans [Ioc]`http://www.fantomfactory.org/pods/afIoc` services for ones
	** that implement `SitemapSource`. URLs generated by these services are then added to the list.
	** 
	** Defaults to 'true'
	static const Str scanIocServices	:= "afSitemap.scanIocServices"

	** If set to 'true', 'Sitemap' automatically adds URLs for [Pillow]`http://www.fantomfactory.org/pods/afPillow` 
	** pages to the list (unless the page an '@InitRender' method with parameters). If the page implements 
	** `SitemapSource` then URLs from the 'sitemapUrls' method are added instead. 
	** 
	** Defaults to 'true'
	static const Str scanPillowPages	:= "afSitemap.scanPillowPages"
}
